# Deploy Spring Boot JAR to Azure Web App (Java SE)
name: Build and deploy JAR app to Azure Web App - CLC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # For OIDC auth with Azure
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List downloaded files
        run: dir

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2D95229631164CD98536F5659AAC94D5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F4CB9356698C4BDCBE92B7576D72EEC1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D1CE64DC052E47E0BED6A397CE037BEB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CLC'
          slot-name: 'Production'
          package: '*.jar' # Adjust if needed based on actual file name

          


